drop table if exists user_tbl CASCADE;
drop table if exists bank_account_tbl CASCADE;
drop table if exists card_tbl CASCADE;
drop table if exists counterparty_tbl CASCADE;
drop table if exists payment_tbl CASCADE;


create table user_tbl
(
    user_id   int generated by default as identity,
    firstname varchar(255) not null,
    lastname  varchar(255) not null,
    primary key (user_id)
);

create table bank_account_tbl
(
    bank_account_id int generated by default as identity,
    number          varchar(255) not null unique,
    money           decimal(10, 2) not null,
    user_id         int not null,
    primary key (bank_account_id),
    foreign key (user_id) references user_tbl (user_id)
);


create table card_tbl
(
    card_id         int generated by default as identity,
    number          varchar(255) not null unique,
    bank_account_id int not null,
    is_active       boolean default false,
    primary key (card_id),
    foreign key (bank_account_id) references bank_account_tbl (bank_account_id)
);

create table counterparty_tbl
(
    counterparty_id      int generated by default as identity,
    bank_account_from_id int not null,
    bank_account_to_id   int not null,
    is_active            boolean default true,
    primary key (counterparty_id),
    foreign key (bank_account_from_id) references bank_account_tbl (bank_account_id),
    foreign key (bank_account_to_id) references bank_account_tbl (bank_account_id)
);

create table payment_tbl
(
    payment_id      int generated by default as identity,
    counterparty_id int not null,
    money           decimal(10, 2) not null,
    is_accepted     boolean default false,
    primary key (payment_id),
    foreign key (counterparty_id) references counterparty_tbl (counterparty_id)
);

INSERT INTO user_tbl (firstname, lastname)
VALUES ('Denis', 'Skvortsov'),
       ('Ivan', 'Ivanov'),
       ('Petr', 'Petrov'),
       ('AnyKey', 'AnyKeev')
;

INSERT INTO bank_account_tbl (number, money, user_id)
VALUES ('11111', 1000, 1),
       ('12222', 4000, 1),
       ('21111', 3457, 2),
       ('31111', 4500, 3),
       ('41111', 5678, 4),
       ('42222', 4567, 4)
;

INSERT INTO card_tbl (number, bank_account_id, is_active)
VALUES ('1111111111111111', 1, false),
       ('1111111122222222', 1, true),
       ('2222222222222222', 2, true),
       ('3333333333333333', 3, false),
       ('4444444444444444', 4, true),
       ('5555555555555555', 5, true),
       ('6666666666666666', 6, true)
;

INSERT INTO counterparty_tbl (bank_account_from_id, bank_account_to_id, is_active)
VALUES (1, 2, true),
       (1, 3, true),
       (4, 1, true)
;

INSERT INTO payment_tbl (counterparty_id, money, is_accepted)
VALUES (1, 500, true),
       (2, 1000, true),
       (3, 2000, false)